### ISSUE TITLE
Multimine crash

### ISSUE THREAD

**Issue by aaronhowser1** [AtomicStryker/atomicstrykers-minecraft-mods#469] opened 2023-02-26 20:01 UTC
MultiMine-1.19.2.2

https://gist.github.com/3bbecf71c8da5aafdb0b74db18077ed3

Got this while mining a block and then moving cursor to another block instead

**Comment by AtomicStryker** [comment] 2023-02-26 21:11
Duplicate of this one https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/467, its fixed for 1.19.3 - i dont know if 1.19.3 mods run fine on 1.19.2?

**Comment by aaronhowser1** [comment] 2023-02-26 21:13
The file for it at least isn't set to 1.19.2 compatible, so it can't be used in 1.19.2 modpacks. I'll try manually installing it though.

**Comment by AtomicStryker** [comment] 2023-02-26 21:16
Google says no. Give me a minute and i will build a 1.19.2 version and push it to curse for you

**Comment by aaronhowser1** [comment] 2023-02-26 21:18
Loads and functions fine in 1.19.2! Just needs to be added to the list of versions on the file then.

As an aside, the custom license link on CF goes to a dead website

**Comment by AtomicStryker** [comment] 2023-02-26 21:24
OK that is good, i still pushed 1.19.2.3 to curse which is the latest version of Multi Mine built for 1.19.2

I have also updated the license link on the popular CF projects to point to the current github.io page thanks

**Closed as completed by AtomicStryker** 2023-02-26 21:24 UTC
