### ISSUE TITLE
Infernal Mobs - Mobs not targetting the player still attack with effects.

### ISSUE THREAD

**Issue by SlayerTheChikken** [AtomicStryker/atomicstrykers-minecraft-mods#217] opened 2018-07-10 22:02 UTC
So for example a zombie pigman even non-hostile if it has lightning effect itll strike the player.

**Comment by AtomicStryker** [comment] 2018-07-11 08:54
Duplicate of https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/134

**Closed as completed by AtomicStryker** 2018-07-11 08:54 UTC
Labels: duplicate
