### ISSUE TITLE
[1.14.4] Infernal Mobs with Forge 28.0.92+ freeze MC loading world

### ISSUE THREAD

**Issue by j4p4n4s4** [AtomicStryker/atomicstrykers-minecraft-mods#289] opened 2019-09-15 16:39 UTC
Last working version on Forge 28.0.91, with latest forge versions hangs MC loading world

18:04:25.722
Error executing task on Chunk source main thread executor for minecraft:overworld
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$4666/1016653469.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550)
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:273)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:148)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:452)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:107)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at atomicstryker.infernalmobs.common.EntityEventHandler.onEntityJoinedWorld(EntityEventHandler.java:34)
	at net.minecraftforge.eventbus.ASMEventHandler_202_EntityEventHandler_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:904)
	at net.minecraft.world.server.ChunkManager.lambda$null$24(ChunkManager.java:577)
	at net.minecraft.world.server.ChunkManager$$Lambda$4734/650317542.apply(Unknown Source)
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
	at com.mojang.datafixers.util.Either$$Lambda$4735/42375942.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$25(ChunkManager.java:554)
	at net.minecraft.world.server.ChunkManager$$Lambda$4731/1367352162.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 17 more
18:04:25.750
Error executing task on Chunk source main thread executor for minecraft:overworld
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$4666/1016653469.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550)
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:273)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:148)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:452)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:107)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at atomicstryker.infernalmobs.common.EntityEventHandler.onEntityJoinedWorld(EntityEventHandler.java:34)
	at net.minecraftforge.eventbus.ASMEventHandler_202_EntityEventHandler_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:904)
	at net.minecraft.world.server.ChunkManager.lambda$null$24(ChunkManager.java:577)
	at net.minecraft.world.server.ChunkManager$$Lambda$4734/650317542.apply(Unknown Source)
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
	at com.mojang.datafixers.util.Either$$Lambda$4735/42375942.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$25(ChunkManager.java:554)
	at net.minecraft.world.server.ChunkManager$$Lambda$4731/1367352162.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)

**Comment by erindal** [comment] 2019-09-15 18:20
I can confirm this bug, same log. Using Forge 28.1.1

**Comment by AtomicStryker** [comment] 2019-09-15 18:22
Looks like forge made a breaking change to the API honestly

**Comment by KronoTrigger** [comment] 2019-09-27 18:49
I’m using Forge 28.1.22 and it happens to me as well.

**Comment by Xplodin** [comment] 2019-10-02 04:03
Also happening on the latest forge. which version of forge was this working on?

**Comment by AtomicStryker** [comment] 2019-10-02 07:54
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.14.3/InfernalMobs/build.gradle#L78

It was built on 28.0.55

**Comment by AtomicStryker** [comment] 2019-10-05 06:24
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/2de37e82ed68d3cc0ba72b66ef145d65c38038ec
Should be fixed with this version.

**Comment by j4p4n4s4** [comment] 2019-10-05 10:08
working fine with forge 28.1.34 & 28.1.37 last version. Ty

**Closed as completed** 2019-10-05 13:47 UTC
