### ISSUE TITLE
Minions disappearing -- invisible and then unsummoned!

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#193] opened 2018-04-26 03:56 UTC
Not only are Minions still turning invisible, but after a save and restart, they seem to be unsummoned entirely!  This is your latest version for 1.12.2, uploaded Nov 25, 2017.  Forge 2655.

**Comment by AtomicStryker** [comment] 2018-04-26 08:43
I am aware. But there is no hint as to the cause and i won't debug it.

Duplicate of #69
That was you, even! Shame on you :P

**Closed as completed by AtomicStryker** 2018-04-26 08:43 UTC
Labels: duplicate

**Comment by MentalMouse** [comment] 2018-04-26 11:12
Not quite a duplicate, as the problem is now worse:  After a save/exit and reload, I'm back at "Commit to the Darkness", and need to pay another 8 levels.  (ETA:  That was the first time I S&Red; the second time the minions got unsummoned, but I was able to retrieve them with my staff.)

ISTR another go-round elsewhere (maybe with you) on this point, but in _Minecraft_, a save-and-restart is _supposed_ to preserve the game state exactly.  Minions unsummoning themselves does not square with that.

**Comment by teamaonn** [comment] 2018-04-27 09:08
This is actually a bug with your video drivers! How do I know? Well simple enough all you have to do is TP away to another chunk far off (on my patreon server we use RTP) then when the chunk is unloaded, tp back and your minions will be visable again!


Additionally, there is no otherway to get them back without dismissing them and resummoning them. Yes, I have this same issue on my server, and it happens across multiple computers. We simply ignore it and use them to our best abilities.

PPS: This has been going on for a LONG time with the minions, back as far as 1.8 if I remember right about when I first used them. (Atomic, I love your mods, bt-dubs.)
