### ISSUE TITLE
[MultiMine] Crashes with Global Block Hardness mod.

### ISSUE THREAD

**Issue by Aoigen** [AtomicStryker/atomicstrykers-minecraft-mods#486] opened 2023-11-02 11:41 UTC
Minecraft Version: 1.18.2
Forge Version: 40.2.10

Mod MultiMine Version: 1.18.3
Mod Global Block Hardness Version: 1.19.4 - 1.0.0

The game crashes when I finish mining any blocks in survival mode.
The game crashes when multimining more than 3 blocks.

Behavior confirmed by isolating just the 2 mods, but the following crash log contains all other mods I'm using.

[https://bytebin.lucko.me/HejwOFL1r0](url)

**Comment by Aoigen** [comment] 2023-11-02 11:56
[Update]

The previously mentioned behavior is reproducible even when MultiMine is the only mod installed.

It has nothing to do with Global Block Hardness mod or incompatibity with other mods in general.

Tested with the same Forge version and MultiMine version as stated above.

**Comment by AtomicStryker** [comment] 2023-11-02 12:06
Duplicate of https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/467, should be fixed with newer MultiMine versions. Download the newest 1.18.7 from curse

https://legacy.curseforge.com/minecraft/mc-mods/multi-mine/files/all?filter-game-version=1738749986%3a73250

**Comment by Aoigen** [comment] 2023-11-02 12:25
You are amazing and I am sorry for taking your time. This was mainly caused by curseforge 'filters' under 'Files' tab. I selected 'filter by: 1.18.2 > Forge', and only MultiMine 1.18.3 appears in the list for some reason. Thank you!

**Closed as completed** 2023-11-02 17:47 UTC
